### ISSUE TITLE
Run regular XCM test

### ISSUE THREAD

**Issue by sander2** [interlay/bridge#54]
> idea: cron job in github action on bridge/UI repo to test XCM every X hours with chopsticks to validate that XCM is still working considering runtime upgrades

If we ignore the UI part, it'll be straight forward to test - we can just have a ts script that does a bunch of xcm transfers, and then checks if the tokens arrived. I would suggest doing this in 2 steps:
- [ ] Write TS script to make and check xcm transfers
- [ ] Write a cron job or bash script to start a new chopsticks instance, and to launch the script (and report errors if there are any)

**Comment by nud3l** [comment]
You don't actually need to write a cron job but rather write the cron job as a github action using the `schedule` trigger: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

So something along those lines:

```yml
# in .github/workflows/xcm-prod-test.yml
on:
  schedule:
    - cron: '30 9 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Test XCM Interlay
        run: yarn test ...
      - name: Test XCM Kintsugi
        run: yarn test ...
```
